// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfFsjbvzvk2S1Y7rNlaRPXXa65AsxybWs',
    appId: '1:8729339745:web:884e61ab487b842588c720',
    messagingSenderId: '8729339745',
    projectId: 'study-planner-app-101325',
    authDomain: 'study-planner-app-101325.firebaseapp.com',
    storageBucket: 'study-planner-app-101325.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvZpsh5Yy4GxbQO52sV2vitOq-8ha7Wmg',
    appId: '1:8729339745:android:51596ea4f3725b9b88c720',
    messagingSenderId: '8729339745',
    projectId: 'study-planner-app-101325',
    storageBucket: 'study-planner-app-101325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmCW8uIaueWk6qDYi58PcA6IFFgm-enI',
    appId: '1:8729339745:ios:80e27c37f7304fc588c720',
    messagingSenderId: '8729339745',
    projectId: 'study-planner-app-101325',
    storageBucket: 'study-planner-app-101325.firebasestorage.app',
    iosBundleId: 'com.example.studyPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMmCW8uIaueWk6qDYi58PcA6IFFgm-enI',
    appId: '1:8729339745:ios:80e27c37f7304fc588c720',
    messagingSenderId: '8729339745',
    projectId: 'study-planner-app-101325',
    storageBucket: 'study-planner-app-101325.firebasestorage.app',
    iosBundleId: 'com.example.studyPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfFsjbvzvk2S1Y7rNlaRPXXa65AsxybWs',
    appId: '1:8729339745:web:a97e5cb99c39d01488c720',
    messagingSenderId: '8729339745',
    projectId: 'study-planner-app-101325',
    authDomain: 'study-planner-app-101325.firebaseapp.com',
    storageBucket: 'study-planner-app-101325.firebasestorage.app',
  );
}
